修
Signed-off-by: Guxin12 <2452148391@qq.com>

diff --git a/.github/workflows/builddev.yml b/.github/workflows/builddev.yml
--- a/.github/workflows/builddev.yml
+++ b/.github/workflows/builddev.yml
@@ -44,16 +44,15 @@ jobs:
         unzip -q android-ndk-r29-linux.zip -d .
         rm -f android-ndk-r29-linux.zip
 
-        # 设置环境变量
         echo "ANDROID_NDK_HOME=$GITHUB_WORKSPACE/android-ndk-r29" >> $GITHUB_ENV
         echo "ANDROID_NDK=$GITHUB_WORKSPACE/android-ndk-r29" >> $GITHUB_ENV
 
     - name: Show NDK path
       run: |
         echo "ANDROID_NDK_HOME = $ANDROID_NDK_HOME"
-        ls -la "$ANDROID_NDK_HOME/build/cmake/" || echo "cmake dir not found"
-
-    # ─────────────── 以下为原本的构建流程 ───────────────
+        ls -la "$ANDROID_NDK_HOME" || echo "cmake dir not found"
+        echo "查看其他目录"
+        ls -la "$ANDROID_NDK_HOME/toolchains/llvm/prebuilt" || echo "cmake dir not found"
 
     - name: Build kptools - Android arm64-v8a
       working-directory: ./tools
@@ -65,19 +64,19 @@ jobs:
           -DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake" \
           -DCMAKE_BUILD_TYPE=Release \
           -DANDROID_PLATFORM=android-33 \
-          -DANDROID_ABI=arm64-v8a \
-          ../..
-        cmake --build . --config Release -j$(nproc)
+          -DANDROID_ABI=arm64-v8a ../..
+        cmake --build .
         mv kptools kptools-android 2>/dev/null || true
 
     - name: Build kptools - Linux x86_64
       working-directory: ./tools
       run: |
-        mkdir -p build/linux && cd build/linux
-        cmake .. -DCMAKE_BUILD_TYPE=Release
-        make -j$(nproc)
+        cd build
+        cmake ..
+        make
+        
         mv kptools kptools-linux 2>/dev/null || true
-
+        
     - name: Build kernel kpimg
       working-directory: ./kernel
       run: |
